name: conda_env1
channels:
  # - rapidsai
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11.7
  - numpy
  - pandas
  - pyodbc
  - matplotlib
  # - seaborn
  - ipykernel
  - ipywidgets
  - scikit-learn
  - statsmodels
  # - patsy
  - scipy
  - pyodbc
  # - prophet
  - plotly
  - tqdm
  - pytorch
  - torchvision
  - pandoc
  - nbconvert
  - pip
  - psycopg2
  # - tabulate
  # - nltk
  - dask-cudf
  - cudf
  - pip:
    - polars
    # - datasets
    - pyarrow
    - memory_profiler
    - dotenv
    - requests
    - xgboost 
    - scikit-survival
    - scikit-learn
    # - openai
    - tableone